function handle = plotRobot(pose, varargin)
% PLOTROBOT Plot robot pose
%   H = PLOTROBOT(POSE) Returns handles to line objects.
%   H = PLOTROBOT(__,NAME,VALUE) Additionally specify line properties using
%   one or more NAME, VALUE pairs.

    handle = plot(pose(1), pose(2), 'o', ...
                  [pose(1), pose(1)+cos(pose(3))], ...
                  [pose(2), pose(2)+sin(pose(3))], ...
                  'color', 'r', 'markersize', 15, 'linewidth', 2, ...
                  varargin{:});
end
